export default [
  // Night of the Zealot
  {
    campaign: "Night of the Zealot",
    difficulty: "Easy",
    "+1": 2,
    "0": 3,
    "-1": 3,
    "-2": 2,
    "-3": 0,
    "-4": 0,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 1,
    Tablet: 1,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "Night of the Zealot",
    difficulty: "Standard",
    "+1": 1,
    "0": 2,
    "-1": 3,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 1,
    Tablet: 1,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "Night of the Zealot",
    difficulty: "Hard",
    "+1": 0,
    "0": 3,
    "-1": 2,
    "-2": 2,
    "-3": 2,
    "-4": 1,
    "-5": 1,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 1,
    Tablet: 1,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "Night of the Zealot",
    difficulty: "Expert",
    "+1": 0,
    "0": 1,
    "-1": 2,
    "-2": 2,
    "-3": 2,
    "-4": 2,
    "-5": 1,
    "-6": 1,
    "-7": 0,
    "-8": 1,
    Skull: 2,
    Cultist: 1,
    Tablet: 1,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  // dunwich legacy
  {
    campaign: "The Dunwich Legacy",
    difficulty: "Easy",
    "+1": 2,
    "0": 3,
    "-1": 3,
    "-2": 2,
    "-3": 0,
    "-4": 0,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 1,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Dunwich Legacy",
    difficulty: "Standard",
    "+1": 1,
    "0": 2,
    "-1": 3,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 1,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Dunwich Legacy",
    difficulty: "Hard",
    "+1": 0,
    "0": 3,
    "-1": 2,
    "-2": 2,
    "-3": 2,
    "-4": 1,
    "-5": 1,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 1,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Dunwich Legacy",
    difficulty: "Expert",
    "+1": 0,
    "0": 1,
    "-1": 2,
    "-2": 2,
    "-3": 2,
    "-4": 2,
    "-5": 1,
    "-6": 1,
    "-7": 0,
    "-8": 1,
    Skull: 2,
    Cultist: 1,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  // path to carcosa
  {
    campaign: "The Path to Carcosa",
    difficulty: "Easy",
    "+1": 2,
    "0": 3,
    "-1": 3,
    "-2": 2,
    "-3": 0,
    "-4": 0,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 3,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Path to Carcosa",
    difficulty: "Standard",
    "+1": 1,
    "0": 2,
    "-1": 3,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 3,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Path to Carcosa",
    difficulty: "Hard",
    "+1": 0,
    "0": 3,
    "-1": 2,
    "-2": 2,
    "-3": 2,
    "-4": 1,
    "-5": 1,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 3,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Path to Carcosa",
    difficulty: "Expert",
    "+1": 0,
    "0": 1,
    "-1": 2,
    "-2": 2,
    "-3": 2,
    "-4": 2,
    "-5": 1,
    "-6": 1,
    "-7": 0,
    "-8": 1,
    Skull: 3,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  // The Forgotten Age
  {
    campaign: "The Forgotten Age",
    difficulty: "Easy",
    "+1": 2,
    "0": 3,
    "-1": 2,
    "-2": 1,
    "-3": 1,
    "-4": 0,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 1,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Forgotten Age",
    difficulty: "Standard",
    "+1": 1,
    "0": 3,
    "-1": 1,
    "-2": 2,
    "-3": 1,
    "-4": 0,
    "-5": 1,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 1,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Forgotten Age",
    difficulty: "Hard",
    "+1": 1,
    "0": 2,
    "-1": 1,
    "-2": 1,
    "-3": 2,
    "-4": 1,
    "-5": 0,
    "-6": 1,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 1,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Forgotten Age",
    difficulty: "Expert",
    "+1": 0,
    "0": 1,
    "-1": 1,
    "-2": 2,
    "-3": 3,
    "-4": 2,
    "-5": 0,
    "-6": 1,
    "-7": 0,
    "-8": 1,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 1,
    Autofail: 1,
    "Elder Sign": 1
  },
  // The Circle Undone
  {
    campaign: "The Circle Undone",
    difficulty: "Easy",
    "+1": 2,
    "0": 3,
    "-1": 2,
    "-2": 1,
    "-3": 1,
    "-4": 0,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Circle Undone",
    difficulty: "Standard",
    "+1": 1,
    "0": 2,
    "-1": 2,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Circle Undone",
    difficulty: "Hard",
    "+1": 0,
    "0": 2,
    "-1": 2,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 1,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Circle Undone",
    difficulty: "Expert",
    "+1": 0,
    "0": 1,
    "-1": 2,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 0,
    "-6": 1,
    "-7": 0,
    "-8": 1,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  // The Dream Eaters
  {
    campaign: "The Dream Eaters",
    difficulty: "Easy",
    "+1": 2,
    "0": 3,
    "-1": 2,
    "-2": 2,
    "-3": 0,
    "-4": 0,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 0,
    Cultist: 1,
    Tablet: 2,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Dream Eaters",
    difficulty: "Standard",
    "+1": 1,
    "0": 2,
    "-1": 2,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 0,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 0,
    Cultist: 1,
    Tablet: 2,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Dream Eaters",
    difficulty: "Hard",
    "+1": 0,
    "0": 2,
    "-1": 2,
    "-2": 2,
    "-3": 2,
    "-4": 1,
    "-5": 1,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 0,
    Cultist: 1,
    Tablet: 2,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Dream Eaters",
    difficulty: "Expert",
    "+1": 0,
    "0": 1,
    "-1": 2,
    "-2": 2,
    "-3": 1,
    "-4": 2,
    "-5": 1,
    "-6": 1,
    "-7": 0,
    "-8": 1,
    Skull: 0,
    Cultist: 1,
    Tablet: 2,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  // Labyrinths
  {
    campaign: "The Labyrinths of Lunacy",
    difficulty: "Standard",
    "+1": 1,
    "0": 3,
    "-1": 3,
    "-2": 2,
    "-3": 1,
    "-4": 1,
    "-5": 1,
    "-6": 0,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "The Labyrinths of Lunacy",
    difficulty: "Hard",
    "+1": 1,
    "0": 2,
    "-1": 3,
    "-2": 3,
    "-3": 1,
    "-4": 1,
    "-5": 1,
    "-6": 1,
    "-7": 0,
    "-8": 0,
    Skull: 2,
    Cultist: 0,
    Tablet: 0,
    Tentacle: 0,
    Autofail: 1,
    "Elder Sign": 1
  },
  // Guardians of the Abyss
  {
    campaign: "Guardians of the Abyss",
    difficulty: "Standard",
    "+1": 2,
    "0": 2,
    "-1": 3,
    "-2": 2,
    "-3": 2,
    "-4": 1,
    "-5": 0,
    "-6": 1,
    "-7": 0,
    "-8": 0,
    Skull: 3,
    Cultist: 1,
    Tablet: 1,
    Tentacle: 1,
    Autofail: 1,
    "Elder Sign": 1
  },
  {
    campaign: "Guardians of the Abyss",
    difficulty: "Hard",
    "+1": 1,
    "0": 2,
    "-1": 3,
    "-2": 3,
    "-3": 2,
    "-4": 2,
    "-5": 1,
    "-6": 0,
    "-7": 1,
    "-8": 0,
    Skull: 3,
    Cultist: 1,
    Tablet: 1,
    Tentacle: 1,
    Autofail: 1,
    "Elder Sign": 1
  }
]
